name: Evaluate Quiz Game

on: [pull_request]

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm start &  # Run the server in the background
        shell: bash

      - name: Wait for server to start
        run: sleep 5      # Wait for the server to start

      - name: Run tests
        run: node evaluate.js
